DROP PROCEDURE IF EXISTS agregar_reactivo;
DELIMITER $$
CREATE PROCEDURE agregar_reactivo(pUbicacion   VARCHAR(100), pNombre VARCHAR(100), pFk_Categoria INT, pFk_Unidad INT,
                                  pExistencias DOUBLE)
    BEGIN
        START TRANSACTION;
        INSERT INTO Articulo (Nombre, Ubicacion, CantidadActual, PuntoReorden, Descripcion, TipoArticulo)
            VALUE (pNombre, pUbicacion, pExistencias, 0, '', 1);
        INSERT INTO Reactivo (ArticuloID, EsPrecursor, UnidadMetricaID, Categoria, URLHojaSeguridad)
            VALUE (last_insert_id(), FALSE, pFk_Unidad, pFk_Categoria, '');
        COMMIT;
    END $$
DELIMITER ;


INSERT INTO CategoriaReactivo (Nombre) VALUE ('OXIDANTES');     #id 1
INSERT INTO CategoriaReactivo (Nombre) VALUE ('GENERAL');       #id 2
INSERT INTO CategoriaReactivo (Nombre) VALUE ('INFLAMABLES');   #id 3
INSERT INTO CategoriaReactivo (Nombre) VALUE ('CORROSIVO');     #id 4

INSERT INTO UnidadMetrica (Nombre, Siglas) VALUE ('Litro','L');         #id 1
INSERT INTO UnidadMetrica (Nombre, Siglas) VALUE ('Kilogramo','KG');    #id 2
INSERT INTO UnidadMetrica (Nombre, Siglas) VALUE ('Mililitro','ML');    #id 3
INSERT INTO UnidadMetrica (Nombre, Siglas) VALUE ('Gramo','G');         #id 4
INSERT INTO UnidadMetrica (Nombre, Siglas) VALUE ('Rollo','R');         #id 5
INSERT INTO UnidadMetrica (Nombre, Siglas) VALUE ('KML','KML');         #id 6

call agregar_reactivo('estante metalico','ACIDO ACETICO GLACIAL',1,1,17);
call agregar_reactivo('estante metalico' ,'ACIDO CLORHIDRICO GR. 36.5-38.0%',1,1,35);
call agregar_reactivo('estante metalico','ACIDO NITRICO 69-70%',1,2,7.5);
call agregar_reactivo('D-6','ACIDO PERCLORICO 79%',1,2,11);
call agregar_reactivo('estante metalico','ACIDO SULFURICO CONC',1,1,0);
call agregar_reactivo('E-7','ACIDO SULFURICO TECNICO',1,1,0);
call agregar_reactivo('D-4','ACIDO YODICO',1,4,400);
call agregar_reactivo('bodega laborio','acido adipico',1,2,0.5);
call agregar_reactivo('lab organica','aceite de linaza',1,3,240);
call agregar_reactivo('D-2','ACIDO PERCLORICO AL 20%',1,3,250);
call agregar_reactivo('ESTANT MET','ACIDO PERCLORICO 30%',1,2,11.5);
call agregar_reactivo('ESTANT MET','ACIDO PERCLORICO 70%',1,1,7.5);
call agregar_reactivo('D-1','BROMATO DE POTASIO',1,4,245);
call agregar_reactivo('D-1','Fenantreno',1,4,40);
call agregar_reactivo('F-2','Fenol',1,2,6);
call agregar_reactivo('B-1','Fenoltaleína', 1, 4, 900);
CALL agregar_reactivo('L-2','Ferrocianuro de Potasio/Hexacianoferrato (III) de potasio',1,4,400);
call agregar_reactivo('F-1','Florixil', 1, 4, 400);
CALL agregar_reactivo('L-3','Fluoruro de Potasio',1,4,750);
call agregar_reactivo('laboratorio','Fosfato  monoacido de sodio y potasio', 1, 2, 1.5);
CALL agregar_reactivo('L-3','Fosfato dibasico de POTASIO',1,4,9400);
call agregar_reactivo('L-3', 'Fosfato  monobásico de Potasio', 1, 2, 6.5);
CALL agregar_reactivo('P-2','Fosfato dibasico de sodio anhidro',1,2,7.2);
call agregar_reactivo('J-2','Fosfato diácido de Amonio', 1, 4, 500);
CALL agregar_reactivo('A-1','Fósforo test reactivo-2',1,3,50);
call agregar_reactivo('E-1', 'Fructuosa', 1, 2, 2.25);
CALL agregar_reactivo('L-3','Flalato ácido de Potasio',1,2,5.1);
call agregar_reactivo('I-4', 'Flalimida', 1, 2, 1);
CALL agregar_reactivo('A-2','Fusina Cristal',1,2,400);
call agregar_reactivo('A-2','Fusina para microscopía', 1, 4, 100);
CALL agregar_reactivo('B-1','HIDRATO CLORAL',1,4,250);
call agregar_reactivo('D-1', 'IODATO DE SODIO', 1, 4, 425);
CALL agregar_reactivo('B-3','YODO',1,4,500);
call agregar_reactivo('C-3','OXIDO DE CROMO (III)', 1, 2, 1.5);
CALL agregar_reactivo('B-2','OXIDO DE MANGANESO (IV)',1,2,3.6);
call agregar_reactivo('D-2','ACIDO PERCLORICO AL 20%', 1, 3, 250);
CALL agregar_reactivo('ESTANT MET','ACIDO PERCLORICO 30%',1,2,11.5);
call agregar_reactivo('ESTANT MET', 'ACIDO PERCLORICO 70%', 1, 1, 7.5);
call agregar_reactivo('G','Aceite mineral',2,1,6.5);
call agregar_reactivo('I-4','Acetanilida',2,2,2);
call agregar_reactivo('I-4','Acetanimida',2,2,2.5);
call agregar_reactivo('J-3','Acetato de Amonio',2,2,2);
call agregar_reactivo('K-2','Acetato de Calcio',2,2,1.5);
call agregar_reactivo('K-5','Acetato de Cobre (II)',2,4,239);
call agregar_reactivo('L-5','Acetato de Magnesio',2,2,1.75);
call agregar_reactivo('K-5','Acetato de Plata',2,4,0);
call agregar_reactivo('M-2','Acetato de Plomo (II) trihidratado',2,2,2.5);
call agregar_reactivo('O-1','Acetato de Sodio',2,2,6.3);
call agregar_reactivo('O-1','Acetato de Sodio trihidratado',2,2,2);
call agregar_reactivo('laboratorio 3','Acetaminofen  (4-hidroxiacetanilidad)',2,4,100);
call agregar_reactivo('H-2','Ácido  Fosfomolíbdico',2,4,200);
call agregar_reactivo('H-2','Ácido 3-5 Dinitrobenzoico',2,4,100);
call agregar_reactivo('lab. 3 estante 3','Acido 3-metlbenzoico',2,4,500);
call agregar_reactivo('H-1','Ácido Benzoico',2,2,11);
call agregar_reactivo('H-1','Ácido Bórico',2,2,0);
call agregar_reactivo('H-1','Ácido Butírico',2,1,1);
call agregar_reactivo('H-2','Ácido Cílico',2,4,0);
call agregar_reactivo('H-1','Ácido Cinámico',2,4,100);
call agregar_reactivo('H-1','Ácido Cítrico',2,2,0);
call agregar_reactivo('H-2','Ácido Esteárico',2,2,0);
call agregar_reactivo('Q-1','Ácido Fluorhídrico',2,1,9);
call agregar_reactivo('Q-1','Ácido Fosforico 30%',2,1,3.5);
call agregar_reactivo('Q-2','Ácido Fosfórico 85%',2,1,4);
call agregar_reactivo('H-2','Ácido Fosfotúnstico',2,4,400);
call agregar_reactivo('H-3','Ácido Flalico',2,2,2.5);
call agregar_reactivo('D-2','Ácido Ftálico Anhidro',2,2,0);
call agregar_reactivo('H-3','Ácido Láctico',2,3,900);
call agregar_reactivo('H-1','Ácido Maleico',2,4,500);
call agregar_reactivo('H-2','Ácido Molibdofosfórico',2,4,0);
call agregar_reactivo('H-3','Ácido Oleico',2,1,1);
call agregar_reactivo('laboratorio','Acido oxalico',2,2,1);
call agregar_reactivo('Q-3','Ácido Propanoico',2,1,4);
call agregar_reactivo('G-3','Ácido Salícilico',2,2,4);
call agregar_reactivo('H-3','Ácido Selenoso',2,4,400);
call agregar_reactivo('H-3','Ácido Sulfanílico',2,2,100);
call agregar_reactivo('H-3','Ácido Tánico',2,4,250);
call agregar_reactivo('Q-1','Ácido Tioglicólico',2,1,2.5);
call agregar_reactivo('Q-3','Ácido Tricloroacético',2,3,400);
call agregar_reactivo('H-2','Ácido Úrico',2,4,200);
call agregar_reactivo('E-2' ,'Agar Agar',2,2,3);
call agregar_reactivo('C-2','Alcanfor',2,2,1);
call agregar_reactivo('A-2','Alizarina Indicador',2,4,200);
call agregar_reactivo('A-2','Alizarina Sodio Monosulfato',2,4,100);
call agregar_reactivo('E-2' ,'Almidón',2,2,2.5);
call agregar_reactivo('B-1','Anaranjado de Metilo',2,4,50);
call agregar_reactivo('B-1','Anaranjado G',2,4,360);
call agregar_reactivo('D-2','Anhidro ftálico',2,4,500);
call agregar_reactivo('D-1','Antraceno',2,4,300);
call agregar_reactivo('A-1','Antraquinona Violeta R',2,2,300);
call agregar_reactivo('B-2','Azul de bromofenol',2,4,165);
call agregar_reactivo('B-1','Azul de metileno',2,4,50);
call agregar_reactivo('laboratorio 3','Aspirina  (Acido acetilsalicilico)',2,4,150);
call agregar_reactivo('B-1','azul bromotimol EN BODEG LABORATORIO HAY 15 G',2,4,0);
call agregar_reactivo('bodega lab organica','aceite de bacalao',2,3,600);
call agregar_reactivo('bodega  lab' ,'algodón',2,2,1.6);
call agregar_reactivo('D-2','AZUL DE TIMOL',2,4,50);
call agregar_reactivo('F-1','ANIZALDEHIDO',2,4,100);
call agregar_reactivo('F-2','ARENA DE MAR',2,4,500);
call agregar_reactivo('H-2','ACIDO FOSFOWOLFRAMICO',2,4,75);
call agregar_reactivo('Q-2','ACIDO ORTOFOSFORICO',2,1,2);
call agregar_reactivo('I-4','ANIXIDINA',2,1,700);
call agregar_reactivo('L-3','ACETATO DE MAGNESIO 3H2O',2,2,1750);
call agregar_reactivo('L-4','ACIDO ACETICO DE POTASIO',2,4,100);
call agregar_reactivo('Q-6','AMONIO',2,1,2.5);
call agregar_reactivo('M-1','ANHIDROMOLIBDIC',2,4,500);
call agregar_reactivo('M-2','ACETATO DE PLOMO DIHIDRATADO',2,4,700);
call agregar_reactivo('N-2','ACETATO DE BARIO',2,4,500);
call agregar_reactivo('D-1','Benzofenona',2,4,300);
call agregar_reactivo('P-2','Borato de Sodio 10H2O',2,4,800);
call agregar_reactivo('L-4','Bromuro de Potasio',2,2,2.5);
call agregar_reactivo('Q-5','Bromuro de Potasio (comercial)',2,2,50);
call agregar_reactivo('P-1','Bromuro de Sodio',2,2,2);
call agregar_reactivo('I-3','Bronce en polvo',2,4,500);
call agregar_reactivo('H-2','Bicarbonato de sodio',2,2,5);
call agregar_reactivo('Bodega laboratorio','"Buffer pH 7,01"',2,1,5);
call agregar_reactivo('Bodega laboratorio','"Buffer pH 4,01"',2,1,1);
call agregar_reactivo('Bodega laboratorio','buffer ph 10',2,2,0.5);
call agregar_reactivo('P-1','benzoato de sodio' ,2,1,1);
call agregar_reactivo('G I-3','Carbón Activado',2,2,4);
call agregar_reactivo('J-3','Carbonato de Amonio' ,2,4,300);
call agregar_reactivo('K-2','Carbonato de Calcio',2,2,1.25);
call agregar_reactivo('K-5','Carbonato de Cobre (II)',2,4,50);
call agregar_reactivo('I-2','Carbonato de Magnesio',2,2,1);
call agregar_reactivo('L-1','Carbonato de Níquel',2,2,0.5);
call agregar_reactivo('L-2','Carbonato de Potasio',2,4,500);
call agregar_reactivo('O-3','Carbonato de Sodio',2,2,500);
call agregar_reactivo('K-3','Carburo de Calcio',2,2,3.5);
call agregar_reactivo('E-1','Celulosa Microcristalina',2,2,5);
call agregar_reactivo('E-1','Celulosa Nativa',2,2,1.5);
call agregar_reactivo('L-4','Cianato de Potasio',2,2,1);
call agregar_reactivo('L-2','Cintas de Magnesio',2,5,0.5);
call agregar_reactivo('P-1','Citrato de Sodio 2H2O',2,2,500);
call agregar_reactivo('D-1','Clorancotil Cloride',2,3,50);
call agregar_reactivo('A-1','"CLORURO DE 2.3.5 TRIFENILTRAZOLIO"',2,3,0);
call agregar_reactivo('J-4','Cloruro de Aluminio',2,2,1.5);
call agregar_reactivo('J-3','Cloruro de Amonio',2,2,8);
call agregar_reactivo('M-3','Cloruro de Bario anhidro',2,2,0.5);
call agregar_reactivo('M-3','Cloruro de Bario dihidratado',2,2,3);
call agregar_reactivo('BODEGA LAB','Cloruro de Cadmio',2,2,0);
call agregar_reactivo('K-3','Cloruro de Calcio',2,2,6);
call agregar_reactivo('K-3','Cloruro de Calcio dihidratado',2,2,2.5);
call agregar_reactivo('K-3','Cloruro de Calcio granulado',2,2,1);
call agregar_reactivo('K-5','Cloruro de Cobre (II) dihidratado',2,2,1750);
call agregar_reactivo('L-5','Cloruro de estaño',2,2,4);
call agregar_reactivo('Laboratorio','Cloruro de estroncio',2,4,2);
call agregar_reactivo('N-2','Cloruro de Hierro (III) hexahidratado',2,2,1);
call agregar_reactivo('Laboratorio','Cloruro de litio',2,2,0.1);
call agregar_reactivo('I-1','Cloruro de Magnesio 6 H2O',2,2,1.5);
call agregar_reactivo('M-3','Cloruro de Mercurio (II)',2,2,1.4);
call agregar_reactivo('L-1','Cloruro de Níquel (II)',2,2,1);
call agregar_reactivo('M-2','Cloruro de Plomo',2,4,250);
call agregar_reactivo('L-4','Cloruro de Potasio',2,2,3.5);
call agregar_reactivo('N-3','Cloruro de Sodio',2,4,2900);
call agregar_reactivo('N-3','Cloruro de Zinc',2,2,1);
call agregar_reactivo('K-4','Cobre en lámina',2,2,10);
call agregar_reactivo('K-4','Cobre en polvo',2,2,6);
call agregar_reactivo('L-5','Coloidal de Plata',2,4,20);
call agregar_reactivo('labor 3','caseina',2,2,0.5);
call agregar_reactivo('I-3','CAL',2,2,1);
call agregar_reactivo('K-4','CLORURO DE COBRE (cristales )',2,4,300);
call agregar_reactivo('N-1','CLORURO DE HIERRO 2 CUATRO AGUAS',2,4,1250);
call agregar_reactivo('BODEGA DE LAB','CLORURO DE NIQUEL 6 H2O',2,4,125);
call agregar_reactivo('BODEGA DE LAB','NIQUEL METAL',2,4,500);
call agregar_reactivo('BODEGA DE LAB','COBRE EN TROZOS ( ALAMBRE ) LO TRAE JC',2,2,5452);
call agregar_reactivo('BODEGA DE LAB','cloruro sodio no reactivo',2,2,7.5);
call agregar_reactivo('BODEGA DE LAB','clavos de hierro',2,2,2);
call agregar_reactivo('I-3','DIOXIDO DE SILICIO' ,2,2,2);
call agregar_reactivo('I-5','DIOXIDO DE TITANIO',2,2,1);
call agregar_reactivo('L-3','DIOFTALATO DE POTASIO',2,4,400);
call agregar_reactivo('M-2','DIOXIDO DE PLOMO',2,4,500);
call agregar_reactivo('M-3','DIFENIL-4-SULFONICO',2,4,55);
call agregar_reactivo('C-2','EDTA',2,2,0.1);
call agregar_reactivo('C-1','EDTA (sal disodica)',2,2,5.5);
call agregar_reactivo('laboratorio','eosina amarilla',2,4,75);
call agregar_reactivo('B-1','Eriocromo Negro T',2,4,175);
call agregar_reactivo('L-5','Estaño en polvo',2,4,500);
call agregar_reactivo('BODEGA LAB','Estaño Granulado',2,2,2);
call agregar_reactivo('generales','eosina y',2,2,0.25);
call agregar_reactivo('E-2','Gelatina',2,4,0);
call agregar_reactivo('G-2','Glicerina',2,1,2);
call agregar_reactivo('F-1','Glucosa monohidratada',2,2,3.05);
call agregar_reactivo('F-1','Goma arabiga',2,4,250);
call agregar_reactivo('BODEGA LAB 3','GRASA VEGETAL ( MANTECA )',2,2,1.3);
call agregar_reactivo('A-1','HIERRO REACTIVO' ,2,4,10);

call agregar_reactivo('B-2','Hematoxilina',2,4,200);
call agregar_reactivo('J-2','Heptamolibdato de Amonio tetrahidratado',2,4,1.25);
call agregar_reactivo('L-2','Hexaciano Ferrato (II) de Potasio trihidratado',2,2,2);
call agregar_reactivo('I-5','Hidrocloruro de Hidroxilamina',2,2,0);
call agregar_reactivo('I-5','Hidroquinona',2,2,1);
call agregar_reactivo('L-1','Hidroxicarbonato de Niquel',2,2,1.5);
call agregar_reactivo('Q-6','Hidróxido de Amonio 33%',2,1,16.5);
call agregar_reactivo('M-3','Hidróxido de Bario 8 H2O',2,2,4.5);
call agregar_reactivo('K-1','Hidróxido de Calcio',2,2,1);
call agregar_reactivo('L-2','Hidróxido de Potasio',2,2,2.5);
call agregar_reactivo('O-2','Hidróxido de Sodio',2,2,31.1);
call agregar_reactivo('P-3','Hiposulfito de Sodio',2,4,100);
call agregar_reactivo('L-2','Hidrogenoftalato de potasio',2,2,1400);
call agregar_reactivo('L-3','HIDROGENOFOSFATO DIPOTASIO',2,2,7);
call agregar_reactivo('N-2','HIERRO POLVO',2,4,4000);
call agregar_reactivo('K-2','HIPERCLORATO DE CALCIO',2,2,0.15);
call agregar_reactivo('G-3','HYDROFLUORICACID 48-51%',2,4,500);
call agregar_reactivo('K-2','HIPOCLORITO DE CALCIO (68-72%)Cl2',2,2,6);
call agregar_reactivo('H-1','HYDROQUINONE',2,2,6);
call agregar_reactivo('O-3','HIDROXIDO DE SODIO (análisis)',2,4,2);
call agregar_reactivo('BODEGA LAB','HIERRO METAL ( TUERCAS Y ARANDELAS )',2,2,9301);
call agregar_reactivo('L-4','Indole 3 Acetic Potasio Sal',2,4,100);
call agregar_reactivo('G-2','Iodoformo',2,4,500);
call agregar_reactivo('M-3','Ioduro de Mercurio (II)',2,4,150);
call agregar_reactivo('L-5','Ioduro de Plata',2,4,35);
call agregar_reactivo('L-2','Ioduro de Potasio',2,2,1000);
call agregar_reactivo('P-3','Ioduro de Sodio',2,4,3450);
call agregar_reactivo('bodega laboratorio','jabon liquido ( lavar cristaleria)',2,1,41.6);
call agregar_reactivo('E-1','Lactosa',2,2,6);

call agregar_reactivo('K-1','Manganeso Test Solución 1',2,3,50);
call agregar_reactivo('K-1','Manganeso y Magnesio Test Solución 2',2,6,50);
call agregar_reactivo('M-1','m-Cresol',2,3,250);
call agregar_reactivo('M-3','Mercurio metalico',2,4,0);
call agregar_reactivo('O-2','Metabisulfito de Sodio',2,4,500);
call agregar_reactivo('G-2','Metoxi-4-benzaldehído',2,1,2);
call agregar_reactivo('J-2','Molibdato de Amonio',2,2,1.1);
call agregar_reactivo('J-1','Monovanadato de Amonio',2,4,0);
call agregar_reactivo('A-1','Murexida',2,4,600);
call agregar_reactivo('bod lab 3','maltosa',2,4,100);
call agregar_reactivo('F-3','2-Naftol',2,4,0);
call agregar_reactivo('C-2','Naftaleno',2,2,2);
call agregar_reactivo('P-3','Nitrato de aluminio 9 H2O',2,4,500);
call agregar_reactivo('P-3','Nitrato de bismuto (III) 5H2O',2,4,500);
call agregar_reactivo('Q-8','Nitrato de Calcio tetrahidratado',2,2,4);
call agregar_reactivo('Q-8','Nitrato de Calcio trihidratado',2,2,1);
call agregar_reactivo('P-3','Nitrato de cobre (II) 3 H2O',2,2,2.6);
call agregar_reactivo('N-1','Nitrato de hierro (III) 9 H2O',2,2,1);
call agregar_reactivo('Q-7','Nitrato de Mercurio (I) dihidratado',2,4,0);
call agregar_reactivo('Q-7','Nitrato de Mercurio (II) monohidratado',2,4,250);
call agregar_reactivo('P-3','Nitrato de Níquel II 6H2O',2,2,0);
call agregar_reactivo('L-5','Nitrato de Plata',2,2,0);
call agregar_reactivo('Q-7','Nitrato de Plomo (II)',2,2,8);
call agregar_reactivo('Q-8','Nitrato de Potasio',2,2,5);
call agregar_reactivo('P-3','Nitrato de Sodio',2,2,3);
call agregar_reactivo('A-1','Nitrato reactivo-1',2,3,50);
call agregar_reactivo('Q-7','Nitrito de Sodio',2,2,1.5);
call agregar_reactivo('I-4','o-Anisidina',2,3,800);
call agregar_reactivo('F-1','o-Anizaldehído',2,4,100);
call agregar_reactivo('J-1','Oxalato de Amonio',2,2,1);
call agregar_reactivo('L-4','Oxalato de Potasio monohidratado',2,2,1);
call agregar_reactivo('O-1','Oxalato de Sodio',2,2,1);
call agregar_reactivo('J-4','Óxido de Aluminio',2,4,1.5);
call agregar_reactivo('J-5','Óxido de Aluminio 150 básico',2,2,1.8);
call agregar_reactivo('J-5','Óxido de Aluminio 150 G neutro 150',2,4,150);
call agregar_reactivo('J-5','Óxido de Aluminio 60 básico',2,2,1);
call agregar_reactivo('J-4','Óxido de Aluminio 60 neutro',2,2,2.5);
call agregar_reactivo('J-4','Óxido de Aluminio 90 activi ácido',2,4,900);
call agregar_reactivo('J-4','Óxido de Aluminio 90 neutro',2,4,0);
call agregar_reactivo('J-5','Óxido de Aluminio para Metalografía',2,2,1);
call agregar_reactivo('K-2','Óxido de Calcio',2,2,2);
call agregar_reactivo('K-5','Óxido de Cobre (II)',2,2,1);
call agregar_reactivo('N-2','Óxido de Hierro (III)',2,2,8.8);
call agregar_reactivo('I-1','Óxido de Magnesio',2,2,4.9);
call agregar_reactivo('M-2','Óxido de Manganeso IV',2,4,143);
call agregar_reactivo('M-2','Óxido de Molibdeno (VI)',2,4,550);
call agregar_reactivo('M-2','Óxido de Plomo (IV)',2,4,250);
call agregar_reactivo('I-3','Óxido de Silicio (IV)',2,2,1.4);
call agregar_reactivo('I-3','Óxido de Titanio (IV)',2,2,1);
call agregar_reactivo('N-3','Óxido de Zinc',2,2,2);
call agregar_reactivo('I-5','OFTALEMINA',2,2,1);
call agregar_reactivo('F-1','Parafina',2,2,1);
call agregar_reactivo('M-1','Penta Clorofenol',2,2,2.25);
call agregar_reactivo('F-3','Pentaclorofenol',2,4,500);
call agregar_reactivo('M-2','Plomo en lámina',2,2,300);
call agregar_reactivo('M-2','Plomo Granulado',2,2,0);
call agregar_reactivo('P-3','Polvora negra',2,4,50);
call agregar_reactivo('LAB. 3','P-CLOROANILINA',2,2,3.5);
call agregar_reactivo('L-5','PLATA COLOIDAL',2,4,20);
call agregar_reactivo('BODEGA LAB','PLOMO METAL ( ARANDELAS )',2,2,8200);
call agregar_reactivo('F-3','Resorcina',2,4,250);
call agregar_reactivo('B-2','Rojo Congo',2,4,250);
call agregar_reactivo('B-1','Rojo de Metilo',2,4,135);
call agregar_reactivo('bodega lab','rojo cresol',2,2,0.25);
call agregar_reactivo('bodega lab','rojo clorofenol',2,2,0.5);
call agregar_reactivo('bodega lab' ,'rojo fenol',2,2,0.1);
call agregar_reactivo('bodega lab' ,'rojo brofenol',2,2,0);
call agregar_reactivo('D-2','ROJO METILO',2,2,10);
call agregar_reactivo('P-3','Sacarina Sódica',2,4,50);
call agregar_reactivo('E-1','Sacarosa',2,2,12);
call agregar_reactivo('A-1','Safranina',2,4,50);
call agregar_reactivo('A-2','Safranina O',2,4,400);
call agregar_reactivo('M-3','Sal de bario de difenilamina 4 sulfonico',2,4,0);
call agregar_reactivo('O-3','Selenito de Sodio Pentahidratado',2,4,300);
call agregar_reactivo('I-3','Sílica gel',2,4,5100);
call agregar_reactivo('J-4','Sulfato de Aluminio',2,4,0);
call agregar_reactivo('J-3','Sulfato de Amonio',2,2,1);
call agregar_reactivo('J-3','Sulfato de Amonio y Cerio dihidratado',2,4,100);
call agregar_reactivo('J-1','Sulfato de Amonio y Hierro (III) dodecahidratado',2,2,0);
call agregar_reactivo('K-3','Sulfato de Calcio dihidratado',2,4,1);
call agregar_reactivo('J-3','Sulfato de cerio (IV) tetrahidratado',2,4,2);
call agregar_reactivo('K-4','Sulfato de Cobre (II)',2,2,4);
call agregar_reactivo('K-5','Sulfato de Cobre (II) pentahidratado',2,2,9.5);
call agregar_reactivo('N-1','Sulfato de Hierro (II) heptahidratado',2,2,2.5);
call agregar_reactivo('N-1','Sulfato de Hierro (III) hidratado',2,2,0.5);
call agregar_reactivo('O-3','Sulfato de hierro II y amonio',2,2,1.5);
call agregar_reactivo('I-1','Sulfato de Magnesio',2,2,1);
call agregar_reactivo('I-1','Sulfato de Magnesio - 7H2O',2,2,1.8);
call agregar_reactivo('K-1','Sulfato de Manganeso (II)',2,2,4);
call agregar_reactivo('L-4','Sulfato de Níquel hexahidratado',2,4,400);
call agregar_reactivo('O-3','Sulfato de Sodio Anhidro',2,2,3.5);
call agregar_reactivo('O-3','Sulfato de Sodio decahidratado',2,4,10);
call agregar_reactivo('N-3','Sulfato de Zinc heptahidratado',2,2,0);
call agregar_reactivo('P-3','Sulfito acido de sodio',2,1,1);
call agregar_reactivo('O-3','Sulfito de sodio',2,2,2);
call agregar_reactivo('N-1','Sulfuro de Hierro (II)',2,4,750);
call agregar_reactivo('P-1','Sulfuro de Sodio x hidratado',2,2,750);
call agregar_reactivo('BODEGA LAB','SACAROSA NO REACTIVO ( AZUCAR COMUN)',2,1,4);
call agregar_reactivo('BODEG LABO','INDIGO CARMIN',2,4,25);
call agregar_reactivo('Q-4','Talco',2,2,3);
call agregar_reactivo('L-3','Tartrato de Antimonio y Potasio',2,4,500);
call agregar_reactivo('L-3','Tartrato de Potasio hemihidratado',2,2,1);
call agregar_reactivo('O-3','Tartrato de Sodio dihidratado',2,2,1);
call agregar_reactivo('O-3','Tartrato de Sodio y Potasio',2,4,5);
call agregar_reactivo('P-2','Tetraborato de Sodio 10 H2O',2,4,0.2);
call agregar_reactivo('lab. Organica','Tetracloruro de carbono',2,1,3);
call agregar_reactivo('I-3','Tierra Silicia',2,4,600);
call agregar_reactivo('B-1','Timol cristal',2,4,400);
call agregar_reactivo('J-1','Tiocianato de Amonio',2,2,4);
call agregar_reactivo('L-3','Tiocianato de Potasio',2,2,1);
call agregar_reactivo('O-3','Tiocianato de Sodio',2,2,0.5);
call agregar_reactivo('O-2','Tiosulfato de Sodio 5 H2O',2,2,3.75);
call agregar_reactivo('M-1','Tricloroetileno',2,1,1);
call agregar_reactivo('M-1','Trietanolamina',2,1,3);
call agregar_reactivo('bodega lab','timolftaleina',2,2,0.15);
call agregar_reactivo('D-1','Urea',2,2,0);
call agregar_reactivo('J-1','Vanadato de Amonio',2,4,25);
call agregar_reactivo('Q-4','Vaselina líquida',2,1,0);
call agregar_reactivo('B-2','Verde de Bromocresol',2,4,25);
call agregar_reactivo('B-2','Verde de Malaquita',2,4,400);
call agregar_reactivo('Ubicación General','Violeta Cristal',2,4,175);
call agregar_reactivo('D-2','VERDE METILO',2,4,25);
call agregar_reactivo('P-3','Wolfranato de Sodio dihidratado',2,4,250);
call agregar_reactivo('F-1','XILOSA',2,4,10);
call agregar_reactivo('bodega labor.','Zinc granular', 2, 2, 2735);
call agregar_reactivo('G-2','ACETALDEHIDO',3,1,1.5);
call agregar_reactivo('ESTA MET','ACETATO DE ETILO',3,1,8);
call agregar_reactivo('I-4','ACETONA',3,2,32);
call agregar_reactivo('B-3','ALCOHOL BENCILICO',3,1,1.6);
call agregar_reactivo('A-1','ACIDO FORMICO',3,1,2);
call agregar_reactivo('B-2','ALCOHOL ISOPROPILICO',3,1,0);
call agregar_reactivo('B-1','ALCOHOL Amilico',3,1,11);
call agregar_reactivo('H-4','ALUMINIO EN ALAMBRE',3,4,0);
call agregar_reactivo('H-4','Aluminio EN COLOCHOS',3,2,0);
call agregar_reactivo('H-4','ALUMINIO EN LAMINA',3,2,1);
call agregar_reactivo('H-4','ALUMINIO EN POLVO',3,2,0);
call agregar_reactivo('F-1','ANIHIDRIDO ACETICO',3,1,3);
call agregar_reactivo('G-1','ANILINA',3,1,22.5);
call agregar_reactivo('D-1','AZUFRE',3,4,2500);
call agregar_reactivo('D-1','AZUFRE EN POLVO',3,2,32);
call agregar_reactivo('B-1','ALCOHOL ISOAMILICO',3,2,6);
call agregar_reactivo('B-1','ALCOHOL N-PROPILICO',3,2,7);
call agregar_reactivo('F-1','ALUMBRE DE POTASIO',3,2,1);
call agregar_reactivo('C-2','1-BROMOBUTANO',3,1,1.5);
call agregar_reactivo('C-1','1-BUTANOL',3,1,2);
call agregar_reactivo('C-2','2- BUTANOL',3,1,3.5);
call agregar_reactivo('I-1','BENCENO',3,1,0);
call agregar_reactivo('G-2','BENZALDEHIDO',3,1,0.5);
call agregar_reactivo('J-3','BROMO',3,3,0);
call agregar_reactivo('F-3','BROMOBENCENO',3,1,2.5);
call agregar_reactivo('F-3','MONO-BROMO-BENCENO',3,2,0.5);
call agregar_reactivo('C-2','1-CLORO-2-METIL-2-PROPANOL',3,2,20);
call agregar_reactivo('C-2','1-CLOROBUTANO',3,1,5);
call agregar_reactivo('C-2','2-CLOROBUTANO',3,1,0.5);
call agregar_reactivo('laboratorio','Canfin',3,1,6);
call agregar_reactivo('H-3','CICLOHEXANO',3,1,6);
call agregar_reactivo('C-1','CICLOHEXANOL',3,1,6);
call agregar_reactivo('F-3','CLOROBENCENO',3,1,2);
call agregar_reactivo('G-2','CLORURO DE ACETILO',3,1,2.75);
call agregar_reactivo('H-1','CICLOHEXENO',3,1,2);
call agregar_reactivo('I-2','Cloroformo*',3,1,16);
call agregar_reactivo('A-2','1-4 DIOXANO',3,1,1.4);
call agregar_reactivo('C-1','"2,2-DIETIL PROPANEDIOL"',3,2,2);
call agregar_reactivo('F-1','DEKALIN (C10H18)',3,3,600);
call agregar_reactivo('H-4','DISULFURO DE CARBONO',3,1,12);
call agregar_reactivo('ESTANT META','Diclorometano',3,2,18);
call agregar_reactivo('d-3','2-ETIL BUTIRALDEHIDO',3,1,4);
call agregar_reactivo('E-1','ETANOL',3,1,0);
call agregar_reactivo('B-3','ETANOL ABSOLUTO',3,1,1);
call agregar_reactivo('A-3','ETANOLAMINA',3,1,2);
call agregar_reactivo('ESTANT MET','ETER DE PETROLEO',3,1,31);
call agregar_reactivo('G-4','ETER ETILICO',3,1,3);
call agregar_reactivo('C-2','ETOXY ETANOL',3,1,2);
call agregar_reactivo('H-1','Eter butilico',3,2,4);
call agregar_reactivo('H-2','FORMALDEHIDO',3,1,34);
call agregar_reactivo('F-4','FOSFORO AMORFO',3,2,2.5);
call agregar_reactivo('F-4','FOSFORO BLANCO',3,4,700);
call agregar_reactivo('I-2','FURANO',3,3,200);
call agregar_reactivo('D-2','FURFURAL',3,3,0);
call agregar_reactivo('Bod lab3','1.10 fenantrolina',3,2,0.25);
call agregar_reactivo('F-2','1-HEXENO',3,4,2.1);
call agregar_reactivo('F-2','2-HEXANONA',3,3,100);
call agregar_reactivo('G-4','HEPTANAL',3,3,0);
call agregar_reactivo('C-1','HEXANAL',3,1,2);
call agregar_reactivo('ESTANTE MET','HEXANO',3,1,53.34);
call agregar_reactivo('F-1','LANA DE ACERO',3,2,5);
call agregar_reactivo('ESTANT MET','2-METIL 2 PROPANOL',3,2,5);
call agregar_reactivo('ESTANT MET','METANOL',3,1,9);
call agregar_reactivo('C-1','METHYL ISOBUTYL CETONA',3,2,0);
call agregar_reactivo('G-3','M-XILENO',3,1,5);
call agregar_reactivo('B-2','METIL - PROPIL-CETONA',3,2,6);
call agregar_reactivo('H-4','N-HEPTANO',3,2,2);
call agregar_reactivo('B-4','NIQUEL EN POLVO',3,4,0);
call agregar_reactivo('G-3','O-XILENO',3,3,900);
call agregar_reactivo('LAB DOC  3','1-OCTANOL',3,3,1500);
call agregar_reactivo('I-H2','1-PENTANOL',3,3,1500);
call agregar_reactivo('F-2','1-PENTENO',3,1,0);
call agregar_reactivo('C-3','1-PROPANOL',3,1,1500);
call agregar_reactivo('I-2','2-PENTANOL',3,1,1);
call agregar_reactivo('B-2','2-PENTANONA',3,2,6);
call agregar_reactivo('ESTANT MET','2-PROPANOL',3,1,8);
call agregar_reactivo('F-2','PIRIDINA',3,1,1.5);
call agregar_reactivo('F-1','POTASIO METALICO',3,4,500);
call agregar_reactivo('G-3','P-XILENO',3,3,500);
call agregar_reactivo('G-3','SODIO METALICO',3,2,3);
call agregar_reactivo('H-4','SULFATO DE ALUMINIO Y POTASIO',3,2,1);
call agregar_reactivo('G-4','SILICILATO DE METILO',3,2,1);
call agregar_reactivo('H-3','SULFURO DE CARBONO',3,2,9.5);
call agregar_reactivo('A-1','TETRAHYDROFURANO',3,1,16);
call agregar_reactivo('ESTANT MET','TOLUENO',3,1,12);
call agregar_reactivo('A-1','2.3.5 TRIFENILTETRASOLIO CLORADO',3,4,20);
call agregar_reactivo('G-2','XILENO',3,1,16);
call agregar_reactivo('C-4','CLORATO DE POTASIO',4,2,1.5);
call agregar_reactivo('B-1','AZUL DE BROMOTIMOL',4,4,165);
call agregar_reactivo('C-4','CROMATO DE POTASIO',4,4,0);
call agregar_reactivo('D-2','DICROMATO DE POTASIO',4,2,2);
call agregar_reactivo('C-3','DICROMATO DE SODIO DIHIDRATADO',4,2,1);
call agregar_reactivo('C-2','CROMATO DE SODIO',4,2,2);
call agregar_reactivo('D-2','DICROMATO DE POTASIO 99.9%',4,2,2);
call agregar_reactivo('C-3','DICROMATO DE SODIO DIHIDRATADO',4,2,1);
call agregar_reactivo('B-3','NITRATO DE AMONIO',4,2,3);
call agregar_reactivo('D-2','PENTACLORURO DE ANTIMONIO',4,3,200);
call agregar_reactivo('D-2','PERIODATO DE POTASIO',4,3,150);
call agregar_reactivo('D-2','PERMANGANATO DE POTASIO' ,4,2,1.5);
call agregar_reactivo('ESTANTE MET','PEROXIDO DE HIDROGENO 3%',4,1,10);
call agregar_reactivo('ESTANTE MET','PEROXIDO DE HIDROGENO 33%',4,1,7.4);
call agregar_reactivo('ESTANTE MET','PEROXIDO DE HIDROGENO 20 %',4,1,2);
call agregar_reactivo('C-2','PERSULFATO DE POTASIO',4,2,1.5);
call agregar_reactivo('B-2','SULFATO DE AMONIO Y CERIO 2 AGUAS',4,4,600);
DROP PROCEDURE IF EXISTS agregar_reactivo;

#Borrar los datos de webhost
/*
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE ArticuloPedido;
DELETE FROM Pedido;
ALTER TABLE Pedido AUTO_INCREMENT = 1;
DELETE FROM ListaNegraNotificacionPorUsuario;
ALTER TABLE ListaNegraNotificacionPorUsuario AUTO_INCREMENT = 1;
DELETE FROM Prestamo;
ALTER TABLE Prestamo AUTO_INCREMENT = 1;
DELETE FROM Movimiento;
ALTER TABLE Movimiento AUTO_INCREMENT = 1;
DELETE FROM Reactivo;
ALTER TABLE Reactivo AUTO_INCREMENT = 1;
DELETE FROM Articulo;
ALTER TABLE Articulo AUTO_INCREMENT = 1;
DELETE FROM CategoriaReactivo;
ALTER TABLE CategoriaReactivo AUTO_INCREMENT = 1;
DELETE FROM UnidadMetrica;
ALTER TABLE UnidadMetrica AUTO_INCREMENT = 1;
set FOREIGN_KEY_CHECKS = 1;
*/

#Borrar datos de hostinger
/*
TRUNCATE TABLE Reactivo;
TRUNCATE TABLE Articulo;
TRUNCATE TABLE CategoriaReactivo;
TRUNCATE TABLE UnidadMetrica;
*/